### ISSUE TITLE
Reference to nonexistent `def-`

### ISSUE THREAD

**Issue by daveliepmann** [alex-dixon/from-java-to-clojure#2]
In the second example, you use `def-` in an apparent attempt to define a private var in the manner of `defn-`. However, `def-` [does not exist](https://groups.google.com/d/msg/clojure/NolgUR4KLis/buqfNsg6AwAJ) and [will not be added to core](https://groups.google.com/d/msg/clojure/NolgUR4KLis/PpxAl31xAwAJ).
 
> > Java
> 
> ```java
> String name = "Amit Shekhar";
> final String name = "Amit Shekhar";
> ```
> 
> > Clojure
> 
> ```clojure
> (def- name "Amit Shekhar")
> (def name "Amit Shekhar")
> ```

I really like this resource; I actually wrote something last week that is in the same space but from a different direction. Would you mind a PR that said something like "treat all `def`s as `final` in Clojure, and if you *really really* need to mutate it, use `atom`"?

**Comment by alex-dixon** [comment]
Whoops. Yeah prs welcome. Is (def ^{:private true} foo 42) just a convention?

**Comment by daveliepmann** [comment]
>Is `(def ^{:private true} foo 42)` just a convention?

Old way (["deprecated, but still works"](https://clojure.org/guides/weird_characters#__code_code_and_code_code_metadata)) to set metadata so that the var is private:
```clojure
(def #^{:private true} foo 42)
```

New way, using shorthand:
```clojure
(def ^:private foo 42)
```
